sudo: required
services:
  - docker

before_install:
  - docker build -t chandrazulfikar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chandrazulfikar/docker-react npm run test

deploy:
  provider: elasticbeanstalk 
  region: "ap-southeast-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-070424646876"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

